### PR TITLE
Dev branch

### PR DESCRIPTION
**Pull request by andybeet**
Pull requests:

* [34](https://github.com/NOAA-EDAB/ms-keyrun/pull/34) - Survey length and number calculations
* [35](https://github.com/NOAA-EDAB/ms-keyrun/pull/35) - Length weight coefficients fit to survey data
* [36](https://github.com/NOAA-EDAB/ms-keyrun/pull/36) - Simulated age length data for Hydra fittiind

### CODE REVIEW

**Review by sgaichas — COMMENTED** [review]
@andybeet I have trouble building dev_branch pkgdown locally, fails with this error
```
-- Building function reference -------------------------------------------------
Error : In '_pkgdown.yml', topic must be a known topic name or alias
✖ Not 'realFisheryLencomp'
```

OK, somehow realFisheryLencomp.Rd was deleted from my local branch, restoring it fixed this but my new error is it can't find catchIndex.Rd

```
Error : In '_pkgdown.yml', topic must be a known topic name or alias
✖ Not 'catchIndex'
```

**Comment by andybeet** [comment]
Those files exist on dev_branch. After you switch to dev make sure you rebuild the package

**Comment by sgaichas** [comment]
Funny I thought they would come in with the pull, but I had to document then build to get them. 
My adventure with upgrading R last month means I need to install a bunch of our packages again. 
had to re-install `mscatch` and the real version of `hydradata` to get through most vignettes, but now `survdat` installation fails due to a leftover calc_discards export in the namespace.
Sean is fixing it... stay tuned

**Comment by sgaichas** [comment]
`survdat` has been updated and everything builds locally now.

**Pull request merged**
