### PR TITLE
Sean data

### PR DESCRIPTION
**Pull request by slucey**
Fisheries landings data, aggregated by year and Georges Bank.

### CODE REVIEW

**Comment by andybeet** [comment]
@sgaichas looks good

**Review by sgaichas — APPROVED** [review]
thanks Sean!

**Comment by sgaichas** [comment]
looks like this is failing gitleaks? so just make sure it doesn't overwrite the corrected github action with the last line as
```
     uses: gitleaks/gitleaks-action@v1.6.0
```
Not a big deal though we can just change it back

**Comment by andybeet** [comment]
I think we'll be ok

**Pull request merged**
