### PR TITLE
added ntrips to fisheryLenSampN data set

### PR DESCRIPTION
**Pull request by andybeet**
## Data

* added additional column `ntrips` to `fisheryLenSampN` data set. The number of trips in a year in which fish length samples were taken. Based on Length samples from GB only even for species with unit stock
* added additional variable to `realFisheryLencomp`. Now includes abundance at length in addition to biomass at length

## Code

* updated `get_fishery_length_sample_n` to genearte new `fisheryLenSampN` data
* updated `create_real_fishery_lencomp` to generate data for `realFisheryLencom`

### CODE REVIEW

**Review by sgaichas — COMMENTED** [review]
Thanks! Overall looks good; I've quickly summarized and have 2 questions:
```
mskeyrun::fisheryLenSampN %>% dplyr::group_by(LongName) %>% dplyr::summarise(meanNtrip = mean(ntrips, na.rm=T))
# A tibble: 10 × 2
   LongName            meanNtrip
   <chr>                   <dbl>
 1 Atlantic cod             74.0
 2 Atlantic herring          1  
 3 Atlantic mackerel        27.7
 4 Goosefish                29.4
 5 Haddock                  56.8
 6 Silver hake              78.0
 7 Spiny dogfish            27.7
 8 Winter flounder          79.1
 9 Winter skate            239. 
10 Yellowtail flounder      62.3
```

1. herring always shows only 1 trip, is this because its summarized from other data?
2. is winter skate really all skates?

Herring snippet:
```
as.data.frame(mskeyrun::fisheryLenSampN %>% dplyr::filter(LongName == "Atlantic herring"))
   YEAR SVSPP lensampsize ntrips SPECIES_ITIS         LongName
1  1964    32       27169      1       161722 Atlantic herring
2  1965    32       21386      1       161722 Atlantic herring
3  1966    32       14810      1       161722 Atlantic herring
4  1967    32       16085      1       161722 Atlantic herring
5  1968    32       19635      1       161722 Atlantic herring
6  1969    32       19532      1       161722 Atlantic herring
7  1970    32        8476      1       161722 Atlantic herring
8  1971    32       12204      1       161722 Atlantic herring
9  1972    32       16453      1       161722 Atlantic herring
10 1973    32        8919      1       161722 Atlantic herring
11 1974    32       22982      1       161722 Atlantic herring
12 1975    32       24156      1       161722 Atlantic herring
13 1976    32       31957      1       161722 Atlantic herring
14 1977    32       33037      1       161722 Atlantic herring
15 1978    32       28216      1       161722 Atlantic herring
16 1979    32       37294      1       161722 Atlantic herring
17 1980    32       28315      1       161722 Atlantic herring
18 1981    32       23528      1       161722 Atlantic herring
19 1982    32       12696      1       161722 Atlantic herring
20 1983    32       11015      1       161722 Atlantic herring
21 1984    32       10095      1       161722 Atlantic herring
22 1985    32        8988      1       161722 Atlantic herring
23 1986    32        4746      1       161722 Atlantic herring
24 1987    32        6394      1       161722 Atlantic herring
25 1988    32        6540      1       161722 Atlantic herring
26 1989    32        6300      1       161722 Atlantic herring
27 1990    32        8574      1       161722 Atlantic herring
28 1991    32        8163      1       161722 Atlantic herring
29 1992    32       11543      1       161722 Atlantic herring
30 1993    32        7936      1       161722 Atlantic herring
31 1994    32        4472      1       161722 Atlantic herring
32 1995    32        6183      1       161722 Atlantic herring
33 1996    32        7481      1       161722 Atlantic herring
34 1997    32       10905      1       161722 Atlantic herring
35 1998    32        9156      1       161722 Atlantic herring
36 1999    32       10446      1       161722 Atlantic herring
37 2000    32        9159      1       161722 Atlantic herring
38 2001    32       10178      1       161722 Atlantic herring
39 2002    32        9640      1       161722 Atlantic herring
40 2003    32        7712      1       161722 Atlantic herring
41 2004    32        7099      1       161722 Atlantic herring
42 2005    32        9280      1       161722 Atlantic herring
43 2006    32       11055      1       161722 Atlantic herring
44 2007    32        7772      1       161722 Atlantic herring
45 2008    32        6359      1       161722 Atlantic herring
46 2009    32        6157      1       161722 Atlantic herring
47 2010    32        6127      1       161722 Atlantic herring
48 2011    32        6248      1       161722 Atlantic herring
49 2012    32        6307      1       161722 Atlantic herring
50 2013    32        6676      1       161722 Atlantic herring
51 2014    32        7210      1       161722 Atlantic herring
52 2015    32        5913      1       161722 Atlantic herring
53 2016    32        4876      1       161722 Atlantic herring
54 2017    32        5812      1       161722 Atlantic herring
55 2018    32        5185      1       161722 Atlantic herring
56 2019    32        3711      1       161722 Atlantic herring

```

**Comment by andybeet** [comment]
ah! you are right. Herring samples from from another db and the trip identifier i was using is wrong. I can fix that easy. 
The skate samples are for winter skate but since the lengths come from the survey the `ntrip` is actually `ntows`... And there are a lot of tows in a survey

**Review by sgaichas — COMMENTED** [review]
Looks good, thanks Andy!
Last question on skates, is that the whole survey or just GB? I was getting annual average ntows for winter skate lengths on GB in the range of 40-50. I may be counting tows incorrectly though.

**Comment by andybeet** [comment]
The landings are for GB but the lengths are the whole shelf since the stock is a unit stock. Same applies for some other species like herring, mackerel, dogfish etc

**Comment by andybeet** [comment]
@sgaichas
1. realFisheryLencomp now includes abundance
2. fisheryLenSampN now only has lengths based on GB footprint.

**Review by sgaichas — COMMENTED** [review]
Thanks, the ntows look good and most catch at length abundance. 
I'm not seeing abundance for spiny dogfish and winter skates--only biomass?

**Comment by andybeet** [comment]
fixing that, apologies. Didn't check the output  and the code skipped the elasmobrachs

**Review by sgaichas — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
