### PR TITLE
survey length weight parameters

### PR DESCRIPTION
**Pull request by andybeet**
Length weight data pulled from survey and LW relationship fit to data. All supporting files included

## Data

* `realBiolPar.rda` - survey length-weight parameters for focal species
* `lengthweightage.rds` - data pull from survey containing length, weight, and age data for focal species

# Documentation

* realBiolPar.r - describing realBiolPar data set
* Vignette  `GBLengthWeight.rmd` displaying table of parameter estimates and plots of resulting fits

## R code

* create_lw_table.r  - creates table of parameters for rmd and the exported lazyloaded data realBiolPar.rda
* clean_lw_data.r - cleans/removes spurious values from the lengthweightage.rds data prior to fitting

### CODE REVIEW

**Review by slucey — COMMENTED** [review]
Files look good...I'm going to pull it down locally and look over the Rmd

**Comment by slucey** [comment]
@andybeet I get this error when trying to build the vignette locally

image

**Comment by slucey** [comment]
Was missing the update to `mscatch`

**Review by slucey — APPROVED** [review]
Looks good

**Review by sgaichas — COMMENTED** [review]
Looks good, but the object I get doesn't have the same columns as the .R file says.  I see that the object should have been renamed in `create_lw_table.R` but overwrite is set to F right now by default. Should work if set to T but I don't want to break anything...

```
mskeyrun::realBiolPar
               species       alpha     beta     sigma
1            Goosefish 0.020501161 2.933227 0.1776597
2         Atlantic cod 0.006856816 3.091336 0.1341488
3      Winter flounder 0.009108170 3.082983 0.1321759
4  Yellowtail flounder 0.005820041 3.109776 0.1423130
5              Haddock 0.007592401 3.068170 0.1157960
6     Atlantic herring 0.006962894 3.081596 0.1469714
7    Atlantic mackerel 0.003102430 3.321004 0.1194443
8        Spiny dogfish 0.002186913 3.139626 0.1351552
9         Winter skate 0.002447348 3.265525 0.1298105
10         Silver hake 0.004216774 3.129475 0.1738018
```

**Comment by andybeet** [comment]
@sgaichas Yep. Good catch. thanks. Hopefully fixed

**Review by sgaichas — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
