### PR TITLE
Dev package--add simulated bottom temp data to mskeyrun

### PR DESCRIPTION
**Pull request by sgaichas**
Should have all needed files to add the simulated survey bottom temperature time series. Also updates the target review dates in readme and adds a minor Rmd change to allow all vignettes to run.

### CODE REVIEW

**Comment by andybeet** [comment]
@sgaichas Apparently there are two files with conflicts that need to be resolved prior to merging. I have looked at both files and cant see the issue. The DESCRIPTION may be a line ending issue but `git status` doesn't show me any problems

**Comment by sgaichas** [comment]
@andybeet I don't understand what the conflicts are either, or why they are "too complex to resolve in the web editor". I'll follow the instructions in "use the command line to resolve conflicts" and see if I can fix it

**Comment by sgaichas** [comment]
@andybeet I think I fixed them, and I think the Rmd one was line endings, because the conflict was the entire file. If we have more of this it might be good to include a .gitattributes file like we have [on the SOE repos](https://github.com/NOAA-EDAB/SOE-MAFMC/blob/master/.gitattributes).

**Comment by andybeet** [comment]
@slucey This looks good

**Review by slucey — APPROVED** [review]
Looks good to me too

**Pull request merged**
